/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package debts

import io.kotlintest.matchers.doubles.plusOrMinus
import io.kotlintest.matchers.doubles.shouldBeExactly
import io.kotlintest.matchers.exactly
import io.kotlintest.shouldBe
import io.kotlintest.specs.StringSpec
import org.joda.time.LocalDate

class LoanTest : StringSpec({
    val annualTerm =  LoanTerm(LocalDate.now(),LocalDate.now().plusYears(1))
    "interest should be 0 with a 0 rate " {
        val loan = Loan (principal = 100.0,
                        interestRate = InterestRate(0.0),
                        loanTerm = annualTerm,
                        paymentFrequency = LoanPaymentFrequency.Once)
        val count = loan.periodicInterestPayment(1)
        count shouldBe 0.0
    }
    "interest should be 10 on a 100 balance with a 10% rate " {
        val loan = Loan (principal = 100.0,
            interestRate = InterestRate(0.1),
            loanTerm = annualTerm,
            paymentFrequency = LoanPaymentFrequency.Once)
        val count = loan.periodicInterestPayment(1)
        count shouldBe 10.0
    }
    "calculate monthly interest payment " {
        with(Loan (principal = 100.0,
                    interestRate = InterestRate(0.1),
                    loanTerm = annualTerm,
                    paymentFrequency = LoanPaymentFrequency.Monthly)){
            for(month in 1..12) {
                periodicInterestPayment(1) shouldBe  ((10.0 / 12.0) plusOrMinus 0.00001)
            }
        }
    }
})